# Generated by Django 5.2.1 on 2025-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveIntegerField()),
            ],
        ),
    ]
